Do not exit on iptable flush error in hipfw init script.
We are running the scripts with set -e, that means every unchecked
command returning an error exits the script. In this case the
function to flash the firewall rules prematurely exited the script
when the rules had already been flushed.
We now check the return value of the flush_iptables() function and
print a notice if an error occurs.

This commit fixes the error return value of the hipfw in bug 795848.

diff --git a/debian/hipl-firewall.init b/debian/hipl-firewall.init
--- a/debian/hipl-firewall.init
+++ b/debian/hipl-firewall.init
@@ -56,6 +56,10 @@ start_hipfw() {
 }
 
 stop_hipfw() {
+    if ! flush_iptables; then
+        echo "Error while flushing HIP firewall rules."
+    fi
+
     # send TERM to hipfw and if it is still running after 3 seconds send KILL
     if start-stop-daemon --stop --retry 3 --oknodo --exec /usr/sbin/hipfw; then
         log_end_msg 0
@@ -71,12 +75,10 @@ case "$1" in
         ;;
     stop)
         log_daemon_msg "Stopping HIP firewall" "hipfw"
-        flush_iptables
         stop_hipfw
         ;;
     restart|force-reload)
         log_daemon_msg "Restarting HIP firewall" "hipfw"
-        flush_iptables
         stop_hipfw
         start_hipfw
         ;;
